language: generic

before_script:
  - sudo apt-get install -y jq

script:
  - bash ./dash-to-dash.sh | tee index.html | grep "DraftJS"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
