name: Build
on:
  pull_request:
  push:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: "chmod +x ${GITHUB_WORKSPACE}/dash-to-dash.sh"
      - run: "${GITHUB_WORKSPACE}/dash-to-dash.sh >${GITHUB_WORKSPACE}/index.html"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .  # The folder the action should deploy.
